$M2_REPO = "C:\Users\唐大帅\.m2\repository"
$CP = @(
    "target/classes",
    "$M2_REPO/org/springframework/boot/spring-boot/3.2.0/spring-boot-3.2.0.jar",
    "$M2_REPO/org/springframework/boot/spring-boot-autoconfigure/3.2.0/spring-boot-autoconfigure-3.2.0.jar",
    "$M2_REPO/org/springframework/boot/spring-boot-starter/3.2.0/spring-boot-starter-3.2.0.jar",
    "$M2_REPO/org/springframework/boot/spring-boot-starter-web/3.2.0/spring-boot-starter-web-3.2.0.jar",
    "$M2_REPO/org/springframework/boot/spring-boot-starter-security/3.2.0/spring-boot-starter-security-3.2.0.jar",
    "$M2_REPO/org/springframework/security/web/6.2.0/spring-security-web-6.2.0.jar",
    "$M2_REPO/org/springframework/security/config/6.2.0/spring-security-config-6.2.0.jar",
    "$M2_REPO/org/springframework/security/core/6.2.0/spring-security-core-6.2.0.jar",
    "$M2_REPO/org/springframework/security/crypto/6.2.0/spring-security-crypto-6.2.0.jar",
    "$M2_REPO/org/springframework/boot/spring-boot-starter-validation/3.2.0/spring-boot-starter-validation-3.2.0.jar",
    "$M2_REPO/org/springframework/spring-core/6.1.1/spring-core-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-context/6.1.1/spring-context-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-web/6.1.1/spring-web-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-webmvc/6.1.1/spring-webmvc-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-beans/6.1.1/spring-beans-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-expression/6.1.1/spring-expression-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-jcl/6.1.1/spring-jcl-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-aop/6.1.1/spring-aop-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-tx/6.1.1/spring-tx-6.1.1.jar",
    "$M2_REPO/org/springframework/spring-jdbc/6.1.1/spring-jdbc-6.1.1.jar",
    "$M2_REPO/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar",
    "$M2_REPO/com/baomidou/mybatis-plus-spring-boot3-starter/3.5.5/mybatis-plus-spring-boot3-starter-3.5.5.jar",
    "$M2_REPO/com/baomidou/mybatis-plus/3.5.5/mybatis-plus-3.5.5.jar",
    "$M2_REPO/com/baomidou/mybatis-plus-core/3.5.5/mybatis-plus-core-3.5.5.jar",
    "$M2_REPO/com/baomidou/mybatis-plus-extension/3.5.5/mybatis-plus-extension-3.5.5.jar",
    "$M2_REPO/com/baomidou/mybatis-plus-annotation/3.5.5/mybatis-plus-annotation-3.5.5.jar",
    "$M2_REPO/org/mybatis/mybatis/3.5.14/mybatis-3.5.14.jar",
    "$M2_REPO/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar",
    "$M2_REPO/io/jsonwebtoken/jjwt-api/0.12.5/jjwt-api-0.12.5.jar",
    "$M2_REPO/io/jsonwebtoken/jjwt-impl/0.12.5/jjwt-impl-0.12.5.jar",
    "$M2_REPO/io/jsonwebtoken/jjwt-jackson/0.12.5/jjwt-jackson-0.12.5.jar",
    "$M2_REPO/com/fasterxml/jackson/databind/jackson-databind/2.15.3/jackson-databind-2.15.3.jar",
    "$M2_REPO/com/fasterxml/jackson/core/jackson-core/2.15.3/jackson-core-2.15.3.jar",
    "$M2_REPO/com/fasterxml/jackson/core/jackson-annotations/2.15.3/jackson-annotations-2.15.3.jar",
    "$M2_REPO/org/projectlombok/lombok/1.18.30/lombok-1.18.30.jar",
    "$M2_REPO/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar",
    "$M2_REPO/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar",
    "$M2_REPO/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar",
    "$M2_REPO/org/apache/poi/poi/5.2.5/poi-5.2.5.jar",
    "$M2_REPO/org/apache/poi/poi-ooxml/5.2.5/poi-ooxml-5.2.5.jar",
    "$M2_REPO/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar",
    "$M2_REPO/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar",
    "$M2_REPO/com/github/virtuald/curvesapi/1.0.1/curvesapi-1.0.1.jar",
    "$M2_REPO/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar",
    "$M2_REPO/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar",
    "$M2_REPO/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar",
    "$M2_REPO/org/hibernate/validator/hibernate-validator/8.0.1.Final/hibernate-validator-8.0.1.Final.jar",
    "$M2_REPO/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar",
    "$M2_REPO/org/apache/commons/commons-io/2.15.1/commons-io-2.15.1.jar"
)

$classpath = $CP -join ";"
Write-Host "Classpath length: $($classpath.Length)"
Write-Host "Starting application..."
java -cp $classpath com.example.hospital.HospitalDrugManagementApplication